#!/bin/bash

#Script that creats new python files

#check if name provided
if [[ ! $1 ]]; then
	echo "Missing argument"
	exit 1
fi

scriptname="$1"
bindir="${HOME}/python"
filename="${bindir}/${scriptname}.py"

#check if it doesnt already exists
if [[ -e $filename ]]; then
	echo "File ${filename} already exists"
	exit 1
fi

#check if directory exists
if [[ ! -d $bindir ]]; then
	echo "Directory ${bindir} doesnt exists"
	exit 1
fi

#create and open script
echo '#!/usr/bin/env python' >> "$filename" 
echo -e '\ndef main():\n\tpass\n\n\n\n\n\n' >> "$filename"
echo -e 'if __name__ == '__main__':\n\tmain()\n\n' >> "$filename"

chmod u+x "$filename"
$EDITOR "$filename"


echo "end"
exit 0




